KITCHEN-BUILD. Oozie CDH specific changes

diff --git a/bigtop-packages/src/common/oozie/do-component-build b/bigtop-packages/src/common/oozie/do-component-build
--- a/bigtop-packages/src/common/oozie/do-component-build
+++ b/bigtop-packages/src/common/oozie/do-component-build
@@ -15,8 +15,6 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 set -x
-
-. `dirname $0`/bigtop.bom
 #
 # Resolve source directory
 #
@@ -86,28 +84,28 @@ if [ "${DO_MAVEN_DEPLOY}" = "deploy" ]; then
   EXTRA_GOALS="${EXTRA_GOALS} source:jar deploy"
 fi
 
-## Update hardcoded version of the Hadoop base to the current HADOOP VERSION
-## This approach might need to be reconsidered once OOZIE-1201 is fixed
-OLD_VERSION="2.0.2-alpha"
-echo "Replacing old target Hadoop version ${OLD_VERSION} with ${HADOOP_VERSION}"
-POM_FILES="${WORKDIR}/hadooplibs/hadoop-2/pom.xml ${WORKDIR}/hadooplibs/hadoop-distcp-2/pom.xml ${WORKDIR}/hadooplibs/hadoop-test-2/pom.xml ${WORKDIR}/pom.xml"
-for pom in $POM_FILES; do
-  sed -i.orig -e "s#${OLD_VERSION}#${HADOOP_VERSION}#" $pom
-  grep ${HADOOP_VERSION} $pom 2>&1 > /dev/null
-  if [ $? != 0 ]; then
-    echo "Could not replace target hadoop version. Check if Oozie targets Hadoop $OLD_VERSION"
-    exit -1
-  fi
-done
+# We need to build twice: once to generate the MR1 sharelib, again to generate the YARN sharelib
+MKDISTRO_OPTIONS="-DskipTests -Dnot.cdh.release.build=false ${EXTRA_GOALS} -Dmaven.repo.local=${HOME}/.m2/repository $@"
 
-# Invoke Oozie build script
-${WORKDIR}/bin/mkdistro.sh -DskipTests -Dhadoop.version=${HADOOP_VERSION} ${EXTRA_GOALS} -Dmaven.repo.local=${HOME}/.m2/repository "$@"
+${WORKDIR}/bin/mkdistro.sh $MKDISTRO_OPTIONS -Pmr1
+MKDISTRO_RESULT_MR1=$?
+if [ "${MKDISTRO_RESULT_MR1}" != "0" ]; then
+  echo "ERROR: mkdistro.sh failed with error ${MKDISTRO_RESULT_MR1}"
+  echo "Build files from failed build: ${WORKDIR}"
+  exit ${MKDISTRO_RESULT_MR1}
+fi
+SHARELIB=./distro/target/oozie-*-distro/oozie-*/oozie-sharelib-*-sharelib.tar.gz
+cp $SHARELIB ./oozie-sharelib-${FULL_VERSION}.tar.gz
+
+${WORKDIR}/bin/mkdistro.sh $MKDISTRO_OPTIONS
 MKDISTRO_RESULT=$?
 if [ "${MKDISTRO_RESULT}" != "0" ]; then
   echo "ERROR: mkdistro.sh failed with error ${MKDISTRO_RESULT}"
   echo "Build files from failed build: ${WORKDIR}"
   exit ${MKDISTRO_RESULT}
 fi
+SHARELIB=./distro/target/oozie-*-distro/oozie-*/oozie-sharelib-*-sharelib.tar.gz
+cp $SHARELIB ./oozie-sharelib-${FULL_VERSION}-yarn.tar.gz
 
 #
 # Expand Oozie TAR and create CDH Ooozie TAR
@@ -153,6 +151,10 @@ rm -rf ${SRCDIR}/target \
        ${SRCDIR}/*.ipr \
        ${SRCDIR}/*.iws 
 
+cat > ${SRCDIR}/cloudera/${RELEASE_ENV_FILENAME} <<EOM
+FULL_VERSION=${FULL_VERSION}
+export FULL_VERSION
+EOM
 cp ${SRCDIR}/LICENSE.txt ${EXPDIR}
 cp ${SRCDIR}/NOTICE.txt ${EXPDIR}
 cd ${EXPDIR}
@@ -164,6 +166,10 @@ cd ${EXPTMPDIR}
 if [ "${URLSAFE_NAME}" != "${ORIGINAL_NAME}" ]; then
   mv ${URLSAFE_NAME} ${ORIGINAL_NAME}
 fi
+
+rm ${ORIGINAL_NAME}/oozie-sharelib-*-sharelib.tar.gz
+mv ${ORIGINAL_NAME}/src/oozie-sharelib-*.tar.gz ${ORIGINAL_NAME}/
+
 tar cfz oozie${VERSION_SUFFIX}.tar.gz ${ORIGINAL_NAME}
 mv oozie${VERSION_SUFFIX}.tar.gz ${BUILDDIR}
 cd ${BUILDDIR}
