Rebasing Hue packaging on Bigtop

diff --git a/bigtop-packages/src/rpm/hue/SOURCES/hue.init b/bigtop-packages/src/rpm/hue/SOURCES/hue.init
--- a/bigtop-packages/src/rpm/hue/SOURCES/hue.init
+++ b/bigtop-packages/src/rpm/hue/SOURCES/hue.init
@@ -21,22 +21,42 @@
 #
 # chkconfig: 2345 90 10
 # description: Hue web server
-# pidfile: /usr/share/hue/pids/supervisor.pid
+# pidfile: /usr/lib/hue/pids/supervisor.pid
 
 . /etc/init.d/functions
 
 LOCKFILE=/var/lock/subsys/hue
-DAEMON=/usr/share/hue/build/env/bin/supervisor # Introduce the server's location here
+DAEMON=/usr/lib/hue/build/env/bin/supervisor # Introduce the server's location here
 LOGDIR=/var/log/hue  # Log directory to use
 PIDFILE=/var/run/hue/supervisor.pid
 USER=hue
-EXEC=/usr/share/hue/build/env/bin/python
+EXEC=/usr/lib/hue/build/env/bin/python
 DAEMON_OPTS="-p $PIDFILE -l $LOGDIR -d"
 HUE_SHUTDOWN_TIMEOUT=15
 
-export PYTHON_EGG_CACHE='/tmp/.hue-python-eggs'
-
 hue_start() {
+        export PYTHON_EGG_CACHE='/tmp/.hue-python-eggs'
+        RE_REGISTER=/usr/lib/hue/.re_register
+        if [ -e $RE_REGISTER ]; then
+            # Do app_reg on upgraded apps. This is a workaround for DISTRO-11.
+            # We can probably take it out after another release.
+            DO="/sbin/runuser -s /bin/bash $USER -c"
+            APP_REG="/usr/lib/hue/tools/app_reg/app_reg.py"
+            # Upgraded apps write their paths in the re_rgister file.
+            RE_REG_LOG=/var/log/hue/hue_re_register.log
+
+            # Make cwd somewhere that $USER can chdir into
+            pushd / > /dev/null
+            $DO "DESKTOP_LOG_DIR=$LOGDIR $EXEC $APP_REG --install $(cat $RE_REGISTER | xargs echo -n)  >> $RE_REG_LOG 2>&1"
+            ok=$?
+            popd > /dev/null
+            if [ $ok -eq 0 ] ; then
+                rm -f $RE_REGISTER
+            else
+                echo "Failed to register some apps: Details in $RE_REG_LOG"
+            fi
+        fi
+
         echo -n "Starting hue: "
         for dir in $(dirname $PIDFILE) $LOGDIR ${PYTHON_EGG_CACHE}
         do
@@ -50,7 +70,7 @@ hue_start() {
             return 0
         fi
         # the supervisor itself will setuid down to $USER
-        env - PATH=$PATH $DAEMON $DAEMON_OPTS
+        env - PATH=/usr/lib/hue/build/env/bin:$PATH $DAEMON $DAEMON_OPTS
         ret=$?
         base=$(basename $0)
         if [ $ret -eq 0 ]; then
