CDH-24361 Build spark tarball that matches upstream tarball

diff --git a/bigtop-packages/src/common/spark/do-component-build b/bigtop-packages/src/common/spark/do-component-build
--- a/bigtop-packages/src/common/spark/do-component-build
+++ b/bigtop-packages/src/common/spark/do-component-build
@@ -17,6 +17,7 @@
 set -ex
 
 if [ -z "$GIT_REPO" ]; then
+
   if [ "x$SCALA_HOME" = "x" ]; then
       echo "SCALA_HOME has to be set before the build can run"
       exit 2
@@ -36,11 +37,19 @@ if [ -z "$GIT_REPO" ]; then
   #        http://maven.40175.n5.nabble.com/Not-finding-artifact-in-local-repo-td3727753.html
   export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m -XX:PermSize=1024m -XX:MaxPermSize=1024m"
 
-  mvn -Pbigtop-dist -Dcdh.build=true -DskipTests $BUILD_OPTS $MAVEN_INST_DEPLOY -Dmaven.repo.local=${HOME}/.m2/repository -fae "$@"
+
+MYMVN=`which mvn`
+if [ -z $MYMVN ] ; then
+  echo "Could not find a maven command, exiting" >&2
+  exit 1
+fi
+
+  ./make-distribution.sh  --mvn $MYMVN --skip-java-test -Dcdh.build=true $BUILD_OPTS 
 
   rm -rf build
   mkdir -p build/spark-${FULL_VERSION}
-  tar zxf assembly/target/spark-assembly_*-dist.tar.gz -C build/spark-${FULL_VERSION}
+
+  mv dist/* build/spark-${FULL_VERSION}
   (cd build ; tar zcf spark-${FULL_VERSION}.tar.gz spark-${FULL_VERSION}/ ; rm -rf spark-${FULL_VERSION}/)
 
 else
