CDH-18159. Update Hadoop/Impala default configuration

diff --git a/bigtop-packages/src/deb/hadoop/hadoop-hdfs.prerm b/bigtop-packages/src/deb/hadoop/hadoop-hdfs.prerm
--- a/bigtop-packages/src/deb/hadoop/hadoop-hdfs.prerm
+++ b/bigtop-packages/src/deb/hadoop/hadoop-hdfs.prerm
@@ -15,28 +15,43 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# postinst script for hadoop
+# prerm script for hadoop-hdfs
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 case "$1" in
-    configure)
-	mkdir -p /var/log/hadoop-hdfs /var/run/hadoop-hdfs || :
-	chgrp -R hadoop /var/log/hadoop-hdfs /var/run/hadoop-hdfs
-	chmod g+w /var/run/hadoop-hdfs /var/log/hadoop-hdfs
-	chown hdfs:hadoop /var/lib/hadoop-hdfs/ /var/lib/hadoop-hdfs/cache /var/run/hadoop-hdfs
-	chmod 0755 /var/lib/hadoop-hdfs /var/run/hadoop-hdfs
-	chmod 1777 /var/lib/hadoop-hdfs/cache
-	update-alternatives --install /etc/hadoop/conf hadoop-conf /etc/hadoop/conf.impala 5
+    remove|upgrade|deconfigure)
+      update-alternatives --remove hadoop-conf /etc/hadoop/conf.impala || :
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 #DEBHELPER#
+
+exit 0
+
+
