CDH-13387: HCatalog 0.11 packaging for C5
Rework of Hive packaging to include HCatalog

diff --git a/bigtop-packages/src/deb/hive/hive-webhcat.prerm b/bigtop-packages/src/deb/hive/hive-webhcat.prerm
--- a/bigtop-packages/src/deb/hive/hive-webhcat.prerm
+++ b/bigtop-packages/src/deb/hive/hive-webhcat.prerm
@@ -1,4 +1,5 @@
 #!/bin/sh
+#
 # Licensed to the Apache Software Foundation (ASF) under one or more
 # contributor license agreements.  See the NOTICE file distributed with
 # this work for additional information regarding copyright ownership.
@@ -14,23 +15,43 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+# prerm script for webhcat 
+#
+# see: dh_installdeb(1)
+
 set -e
 
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 case "$1" in
-    configure)
-        # Install config alternatives
-        update-alternatives  --install /etc/hcatalog/conf hcatalog-conf /etc/hcatalog/conf.dist 30
-        chown hive:hive /var/run/hcatalog || :
-        chown hive:hive /var/log/hcatalog || :
+    remove|upgrade|deconfigure)
+      update-alternatives --remove hive-webhcat-conf /etc/hive-webhcat/conf.dist || :
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 #DEBHELPER#
+
+exit 0
+
+
